/*
    {
        consonant: "",
        subscript: "",
        fullValue: "",
        fullValueIpa: "",
        consonantValue: "",
        consonantValueIpa: "",
        strong: ,
    },
*/

export const consonants = [
  {
    consonant: 'ក',
    subscript: '្ក',
    fullValueIpa: '[kɑː]',
    consonantValueIpa: '[k]',
    fullValue: 'ka',
    consonantValue: 'k',
    strong: true,
  },
  {
    consonant: 'ខ',
    subscript: '្ខ',
    fullValue: 'kha',
    fullValueIpa: '[kʰɑː]',
    consonantValue: 'kh',
    consonantValueIpa: '[kʰ]',
    strong: true,
  },
  {
    consonant: 'គ',
    subscript: '្គ',
    fullValue: 'ko',
    fullValueIpa: '[kɔː]',
    consonantValue: 'k',
    consonantValueIpa: '[k]',
    strong: false,
  },
  {
    consonant: 'ឃ',
    subscript: '្ឃ',
    fullValue: 'kho',
    fullValueIpa: '[kʰɔː]',
    consonantValue: 'kh',
    consonantValueIpa: '[kʰ]',
    strong: false,
  },
  {
    consonant: 'ង',
    subscript: '្ង',
    fullValue: 'ngo',
    fullValueIpa: '[ŋɔː]',
    consonantValue: 'ng',
    consonantValueIpa: '[ŋ]',
    strong: false,
  },
  {
    consonant: 'ច',
    subscript: '្ច',
    fullValue: 'cha',
    fullValueIpa: '[cɑː]',
    consonantValue: 'ch',
    consonantValueIpa: '[c]',
    strong: true,
  },
  {
    consonant: 'ឆ',
    subscript: '្ឆ',
    fullValue: 'chha',
    fullValueIpa: '[cʰɑː]',
    consonantValue: 'chh',
    consonantValueIpa: '[cʰ]',
    strong: true,
  },
  {
    consonant: 'ជ',
    subscript: '្ជ',
    fullValue: 'cho',
    fullValueIpa: '[cɔː]',
    consonantValue: 'ch',
    consonantValueIpa: '[c]',
    strong: false,
  },
  {
    consonant: 'ឈ',
    subscript: '្ឈ',
    fullValue: 'chho',
    fullValueIpa: '[cʰɔː]',
    consonantValue: 'chh',
    consonantValueIpa: '[cʰ]',
    strong: false,
  },
  {
    consonant: 'ញ',
    subscript: '្ញ',
    fullValue: 'nho',
    fullValueIpa: '[ɲɔː]',
    consonantValue: 'nh',
    consonantValueIpa: '[ɲ]',
    strong: false,
  },
  {
    consonant: 'ដ',
    subscript: '្ដ',
    fullValue: 'da',
    fullValueIpa: '[ɗɑː]',
    consonantValue: 'd',
    consonantValueIpa: '[ɗ]',
    strong: true,
  },
  {
    consonant: 'ឋ',
    subscript: '្ឋ',
    fullValue: 'tha',
    fullValueIpa: '[tʰɑː]',
    consonantValue: 'th',
    consonantValueIpa: '[tʰ]',
    strong: true,
  },
  {
    consonant: 'ឌ',
    subscript: '្ឌ',
    fullValue: 'do',
    fullValueIpa: '[ɗɔː]',
    consonantValue: 'd',
    consonantValueIpa: '[ɗ]',
    strong: false,
  },
  {
    consonant: 'ថ',
    subscript: '្ថ',
    fullValue: 'tha',
    fullValueIpa: '[tʰɑː]',
    consonantValue: 'th',
    consonantValueIpa: '[tʰ]',
    strong: true,
  },
  {
    consonant: 'ឍ',
    subscript: '្ឍ',
    fullValue: 'tho',
    fullValueIpa: '[tʰɔː]',
    consonantValue: 'th',
    consonantValueIpa: '[tʰ]',
    strong: false,
  },
  {
    consonant: 'ណ',
    subscript: '្ណ',
    fullValue: 'na',
    fullValueIpa: '[nɑː]',
    consonantValue: 'n',
    consonantValueIpa: '[n]',
    strong: true,
  },
  {
    consonant: 'ត',
    subscript: '្ត',
    fullValue: 'ta',
    fullValueIpa: '[tɑː]',
    consonantValue: 't',
    consonantValueIpa: '[t]',
    strong: true,
  },
  {
    consonant: 'ទ',
    subscript: '្ទ',
    fullValue: 'to',
    fullValueIpa: '[tɔː]',
    consonantValue: 't',
    consonantValueIpa: '[t]',
    strong: false,
  },
  {
    consonant: 'ធ',
    subscript: '្ធ',
    fullValue: 'tho',
    fullValueIpa: '[tʰɔː]',
    consonantValue: 'th',
    consonantValueIpa: '[tʰ]',
    strong: false,
  },
  {
    consonant: 'ន',
    subscript: '្ន',
    fullValue: 'no',
    fullValueIpa: '[nɔː]',
    consonantValue: 'n',
    consonantValueIpa: '[n]',
    strong: false,
  },
  {
    consonant: 'ប',
    subscript: '្ប',
    fullValue: 'ba',
    fullValueIpa: '[ɓɑː]',
    consonantValue: 'b',
    consonantValueIpa: '[p]',
    strong: true,
  },
  {
    consonant: 'ផ',
    subscript: '្ផ',
    fullValue: 'pha',
    fullValueIpa: '[pʰɑː]',
    consonantValue: 'ph',
    consonantValueIpa: '[pʰ]',
    strong: true,
  },
  {
    consonant: 'ព',
    subscript: '្ព',
    fullValue: 'po',
    fullValueIpa: '[pɔː]',
    consonantValue: 'p',
    consonantValueIpa: '[p]',
    strong: false,
  },
  {
    consonant: 'ភ',
    subscript: '្ភ',
    fullValue: 'pho',
    fullValueIpa: '[pʰɔː]',
    consonantValue: 'ph',
    consonantValueIpa: '[pʰ]',
    strong: false,
  },
  {
    consonant: 'ម',
    subscript: '្ម',
    fullValue: 'mo',
    fullValueIpa: '[mɔː]',
    consonantValue: 'm',
    consonantValueIpa: '[m]',
    strong: false,
  },
  {
    consonant: 'យ',
    subscript: '្យ',
    fullValue: 'yo',
    fullValueIpa: '[jɔː]',
    consonantValue: 'y',
    consonantValueIpa: '[j]',
    strong: false,
  },
  {
    consonant: 'រ',
    subscript: '្រ',
    fullValue: 'ro',
    fullValueIpa: '[rɔː]',
    consonantValue: 'r',
    consonantValueIpa: '[r]',
    strong: false,
  },
  {
    consonant: 'ល',
    subscript: '្ល',
    fullValue: 'lo',
    fullValueIpa: '[lɔː]',
    consonantValue: 'l',
    consonantValueIpa: '[l]',
    strong: false,
  },
  {
    consonant: 'វ',
    subscript: '្វ',
    fullValue: 'vo',
    fullValueIpa: '[ʋɔː]',
    consonantValue: 'v',
    consonantValueIpa: '[ʋ]',
    strong: false,
  },
  {
    consonant: 'ស',
    subscript: '្ស',
    fullValue: 'sa',
    fullValueIpa: '[sɑː]',
    consonantValue: 's',
    consonantValueIpa: '[s]',
    strong: true,
  },
  {
    consonant: 'ហ',
    subscript: '្ហ',
    fullValue: 'ha',
    fullValueIpa: '[hɑː]',
    consonantValue: 'h',
    consonantValueIpa: '[h]',
    strong: true,
  },
  {
    consonant: 'អ',
    subscript: '្អ',
    fullValue: '’a',
    fullValueIpa: '[ʔɑː]',
    consonantValue: '’',
    consonantValueIpa: '[ʔ]',
    strong: true,
  },
]
